name: build on windows

on:
  push:
    branches: [jnh]
  pull_request:
    types: [synchronize, opened]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: msvcsetup
        uses: ilammy/msvc-dev-cmd@v1

      - name: nhsetup
        run: sys/windows/nhsetup

      - name: buildmain
        run: |
          cd src
          nmake GIT=1 package

      - name: tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: ncipollo/release-action@v1 #https://github.com/ncipollo/release-action/tree/main
        with:
          name: "latest"
          allowUpdates: true
          tag: latest
          commit: jnh
          replacesArtifacts: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: package/nethack-370-win-x64.zip

      - name: notify
        uses: sarisia/actions-status-discord@v1
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          status: ${{ job.status }}
